title: "My Art Portfolio & Resume"
description: "A showcase of my latest artwork and technical experience."

show_downloads: false
google_analytics: "UA-XXXXXXXXX-X"

remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
