title: "art_portfolio_&_resume:~$"
description: "A look into some of my personal projects and professional experience."


# This theme explicitly supports the GitHub Pages remote_theme plugin
remote_theme: b2a3e8/jekyll-theme-console

# These settings customize the retro terminal behavior
theme_config:
  appearance: "dark" # Keeps it looking like a CRT monitor
  monospaced_font: true


# This automatically lists these pages in a neat terminal-style header menu!
header_pages:
  - index.md
  - resume.md

  
plugins:
  - jekyll-remote-theme
