title: "art_portfolio_&_resume:~$"
description: "A look into some of my personal projects and professional experience."

# We use a highly customizable terminal theme repo here
remote_theme: mdo/terminal

# These settings customize the retro terminal behavior
theme_config:
  appearance: "dark" # Keeps it looking like a CRT monitor
  monospaced_font: true

plugins:
  - jekyll-remote-theme
